name: 'Get YAML Value'
version: 0.1.0
description: 'Given a valid Semver, update the tags on the github repo.'
inputs:
  file: 
    description: 'YAML file to read'
  key:
    description: "Key to get, dot-seperated levels ('first_level.2.value')"
  venv_path:
    description: Venv path for action
    default: /tmp/semver-to-tag
outputs:
  value:
    description: "Returned value"
    value: ${{ steps.get_value.outputs.value }}

runs:
  using: "composite"
  steps:

    - name: Create venv
      uses: ajparsons/cache-requirements-txt@main
      with:
        python_version: "3.10"
        requirements_path: ${{github.action_path}}/requirements.txt
        cache_key: yaml-reader
        venv_path: ${{ inputs.venv_path }}

    - name: Get value
      id: get_value
      shell: bash
      run: |
        source $VENV_PATH/bin/activate
        python ${{ github.action_path }}/get_key.py
      env:
        YAML_FILE: ${{ inputs.file }}
        YAML_KEY: ${{ inputs.key }}
        VENV_PATH: ${{ inputs.venv_path }}