name: 'Get Config Value'
version: 0.1.0
description: 'Given a JSON/YAML/TOML file, extract a value given by the key.'
inputs:
  file: 
    description: 'Config file to read'
  key:
    description: "Key to get, dot-seperated levels ('first_level.2.value')"
  venv_path:
    description: Venv path for action (optional)
    default: /tmp/get-config-value-venv
outputs:
  value:
    description: "Returned value"
    value: ${{ steps.get_value.outputs.value }}

runs:
  using: "composite"
  steps:

    - name: Create venv
      uses: ajparsons/cache-requirements-txt@47418e65d909c8ab0b403a7c1f6471f14568e75d # v1.0.0
      with:
        python_version: "3.10"
        requirements_path: ${{github.action_path}}/requirements.txt
        cache_key: config-reader
        venv_path: ${{ inputs.venv_path }}

    - name: Get value
      id: get_value
      shell: bash
      run: |
        source $VENV_PATH/bin/activate
        python ${{ github.action_path }}/get_key.py
      env:
        CONFIG_FILE: ${{ inputs.file }}
        CONFIG_KEY: ${{ inputs.key }}
        VENV_PATH: ${{ inputs.venv_path }}