name: 'Get YAML Value'
version: 0.0.1
description: 'Given a valid Semver, update the tags on the github repo.'
inputs:
  file: 
    description: 'YAML file to read'
  key:
    description: "Key to get, dot-seperated levels ('first_level.2.value')"
outputs:
  value:
    description: "Returned value"
    value: ${{ steps.get_value.outputs.value }}

env:
  VENV_PATH: /tmp/semver-to-tag

runs:
  using: "composite"
  steps:

    - name: Cache venv
      id: cache-env
      uses: actions/cache@v3
      with:
        path: ${{ env.VENV_PATH }}
        key: ${{ runner.os }}-venv-yaml-reader-${{ hashFiles(concat(github.action_path,'/requirements.txt')) }}

    - name: Setup python
      uses: actions/setup-python@v4
      if: ${{ steps.cache-env.cache-hit == 'false' }}
      id: python
      with:
        python-version: '3.10' 
        update-environment: false

    - name: Setup venv
      if: ${{ steps.cache-env.cache-hit == 'false' }}
      id: setup_venv
      shell: bash
      run: |
        ${{ steps.python.outputs.python-path }} -m venv $VENV_PATH
        source $VENV_PATH/bin/activate
        pip install -r ${{ github.action_path }}/requirements.txt
  
    - name: Get value
      id: get_value
      shell: bash
      run: |
        source $VENV_PATH/bin/activate
        python ${{ github.action_path }}/get_key.py
      env:
        YAML_FILE: ${{ inputs.file }}
        YAML_KEY: ${{ inputs.key }}